### ISSUE TITLE
HL-L3230CDW // Unknown versioncheck response for firmid=SUB5

### ISSUE THREAD

**Issue by marioli** [sedrubal/brother_printer_fwupd#10]
Hi sedrubal,

great Job that you are able to separate the tasks of the update utility. According to the Brother Homepage my printer has a firmware available (1.37) but the update utility is unable to find a printer in the network. Your script did not receive an udpate URL. Possible that the request XML differs for the HL-L3230CDW?

Thank you.

brother_printer_fwupd -p 172.31.255.210 --debug
[i] Querying printer info via SNMP.
[i] Detected HL-L3230CDW series with following firmware version(s): MAIN@1.34, SUB5@1.00
[i] Querying firmware download URL from Brother update API.
[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>MAIN</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>HL-L3230CDW series</NAME>
            <SPEC>0203</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>

        <FIRM>
            <ID>MAIN</ID>
            <VERSION>1.34</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>

            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO></RESPONSEINFO>
[!] Did not receive download url for MAIN.
[!] Either this firmware part is up to date or there is a bug.
[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB5</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>HL-L3230CDW series</NAME>
            <SPEC>0203</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>

        <FIRM>
            <ID>MAIN</ID>
            <VERSION>1.34</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>

            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK></FIRMUPDATEINFO></RESPONSEINFO>
[!] Unknown versioncheck response for firmid=SUB5.
[!] There seems to be a bug.
[!] Open an issue with the full debug output: https://github.com/sedrubal/brother_printer_fwupd/issues/new
[i] Done.

**Comment by sedrubal** [comment]
Hi @marioli, thanks for your report. It's difficult to debug these errors as I don't have a deeper understanding of the XML the tool is crafting and sending to the API and the responses. AFAIK the update URL should be correct, even for your printer model, as I can find it in the update binary for your printer. So most likely the content of the XML document must be different.
Alternatively, we could try to get the firmware binaries from somewhere else...
I'm sorry. I think there is nothing I can do right now.
