### ISSUE TITLE
DCP-L3550CDW  empty Sub5

### ISSUE THREAD

**Issue by Mousketeer** [sedrubal/brother_printer_fwupd#11]
Using version 0.4.2 (from pypi) I get this - not sure what it means

`brother_printer_fwupd --debug  -p 192.168.1.32
[i] Querying printer info via SNMP.
[i] Detected DCP-L3550CDW series with following firmware version(s): MAIN@Z2203011303:5323, SUB1@1.60, SUB5@1.00
[i] Querying firmware download URL from Brother update API.
[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>MAIN</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>DCP-L3550CDW series</NAME>
            <SPEC>0103</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>
                
        <FIRM>
            <ID>MAIN</ID>
            <VERSION>Z2203011303:5323</VERSION>
        </FIRM>
        
        <FIRM>
            <ID>SUB1</ID>
            <VERSION>1.60</VERSION>
        </FIRM>
        
        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>
        
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO></RESPONSEINFO>
[!] Did not receive download url for MAIN.
[!] Either this firmware part is up to date or there is a bug.
[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB1</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>DCP-L3550CDW series</NAME>
            <SPEC>0103</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>
                
        <FIRM>
            <ID>MAIN</ID>
            <VERSION>Z2203011303:5323</VERSION>
        </FIRM>
        
        <FIRM>
            <ID>SUB1</ID>
            <VERSION>1.60</VERSION>
        </FIRM>
        
        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>
        
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>1</VERSIONCHECK><FIRMID>SUB1</FIRMID></FIRMUPDATEINFO></RESPONSEINFO>
[i] Firmware part SUB1 seems to be up to date.
[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB5</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>DCP-L3550CDW series</NAME>
            <SPEC>0103</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>
                
        <FIRM>
            <ID>MAIN</ID>
            <VERSION>Z2203011303:5323</VERSION>
        </FIRM>
        
        <FIRM>
            <ID>SUB1</ID>
            <VERSION>1.60</VERSION>
        </FIRM>
        
        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>
        
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK><FIRMID>SUB5</FIRMID></FIRMUPDATEINFO></RESPONSEINFO>
[!] Unknown versioncheck response for firmid=SUB5.
[!] There seems to be a bug.
[!] Open an issue with the full debug output: https://github.com/sedrubal/brother_printer_fwupd/issues/new
[i] Done.
`

**Comment by sedrubal** [comment]
Hi @Mousketeer, thanks for your report. It's difficult to debug these errors as I don't have a deeper understanding of the XML the tool is crafting and sending to the API and the responses.
I'm sorry. I think there is nothing I can do right now.

**Comment by Mousketeer** [comment]
No problem, thanks anyway :-)
