### ISSUE TITLE
Support for ADS-4700W

### ISSUE THREAD

**Issue by darix** [sedrubal/brother_printer_fwupd#12]
1. it has a fun line in the snmpwalk output:

```
SNMPv2-SMI::enterprises.2435.2.4.3.99.3.1.6.1.2.11 = STRING: "^L"
```

For this I adapted the code from:

```python
            if not data:
                break
```
to

```python
            if not data or data == "^L":
                break
```

2. no matter if  FIRMID  is set to MAIN or SUB3 and the response for the query is:

```
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK></FIRMUPDATEINFO></RESPONSEINFO>
```

**Comment by sedrubal** [comment]
Hi @darix thanks for sharing this. Would you mind opening a pull request?

**Comment by sedrubal** [comment]
I'll close this issue due to the lack of feedback. Feel free to reopen it as soon as you can provide more information that can be used for a fix.
