### ISSUE TITLE
Not sure which settings I need to download the firmware for the MFC-7860DW

### ISSUE THREAD

**Issue by linganvm** [sedrubal/brother_printer_fwupd#14]
Hi,

Great tool and wonderful site, its just I'm in a dillema where I don't have a working printer and I need to download the latest firmware.

My printer is the MFC-7860DW - just wondering if anyone has got the right request to get the firmware link.

Thanks in advance.

**Comment by sedrubal** [comment]
Hi @linganvm, sorry for the late reply. In version 0.5.1, I added a `--download-only` flag to just download the firmware. The command should look somehow like this:

```sh
brother_printer_fwupd --model "MFC-7860DW" --serial "1234" --spec "0706" --fw "MAIN@W2109141139:E619" --download-only
```

But unfortunately, if you don't have access to the printer, you must guess the required parameters `--serial`, `--spec` and `--fw` (for currently running firmware versions). I hope this helps.
