### ISSUE TITLE
MFC-L3750CDW

### ISSUE THREAD

**Issue by skissane** [sedrubal/brother_printer_fwupd#19]
This tool doesn't work with MFC-L3750CDW – but https://github.com/CauldronDevelopmentLLC/oh-brother does

The difference seems to be in the XML request being sent:
1. In `<MODELINFO>`, your tool sends `<SERIALNO></SERIALNO>`, that other tool sends `<SELIALNO>` (yes terrible spelling is necessary) with the actual printer serial as contents
2. Your tools sends `<DRIVER></DRIVER>`, theirs sends `<DRIVER>EWS</DRIVER>`

Your tool doesn't get back a response, that other tool gets something like this:
```
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>0</VERSIONCHECK><MEMORYVERSION>a</MEMORYVERSION><FIRMID>MAIN</FIRMID><LATESTVERSION>ZD2307031905</LATESTVERSION><PATH>http://update-akamai.brother.co.jp/CS/D00KJY_ZD.djf</PATH><DLTIME>180000</DLTIME></FIRMUPDATEINFO></RESPONSEINFO>
```

**Comment by sedrubal** [comment]
Thank you very much! :tada:

I published a new version (0.6.0), which sends a request with the old XML (because it worked before for some models) and if it fails, if applies the modifications that you mentioned. With this changes, I could successfully download the firmware for MFC-L3750CDW.

**Comment by dlenski** [comment]
As described in https://github.com/sedrubal/brother_printer_fwupd/issues/20#issuecomment-2078379285, this hack was  _also_ necessary for my HL-L2360DW printer.

> 1. In `<MODELINFO>`, your tool sends `<SERIALNO></SERIALNO>`, that other tool sends `<SELIALNO>` (yes terrible spelling is necessary) with the actual printer serial as contents
> 2. Your tools sends `<DRIVER></DRIVER>`, theirs sends `<DRIVER>EWS</DRIVER>`


At least for my printer, the "SELIALNO" misspelling _isn't necessary_ to be able to fetch its firmware files, _only_ the `<DRIVER>EWS</DRIVER>` change is needed.

Given that https://github.com/sedrubal/brother_printer_fwupd/commit/565ef037ea8fd9ccc6bd0b03dd7c18120f7f17e6 didn't actually implement sending the printer's serial number as the tag contents, and that some of Brother's own tools send it and others don't, it's a pretty good indication that the SERIALNO/SELIALNO bit is not necessary.

**Comment by sedrubal** [comment]
Thanks @dlenski for this hint. I'll have a look 😉
