### ISSUE TITLE
libxml2-dev and libxlt-dev are required for poetry build of lxml

### ISSUE THREAD

**Issue by asmcc** [sedrubal/brother_printer_fwupd#2]
libxml2-dev and libxlt-dev are required too for successfull build with poetry during install of lxml. Please include it in your dependensy list.
Furthermore you premise python in the version 3.9 as minimal. Is it really required? This version is very new today and is not in all distributions. I changed it to 3.7 and will probe build it with python 3.7.

**Comment by sedrubal** [comment]
I don't know a way to specify system dependencies in the pyproject.toml. If there is one, let me know. I added a comment to the README.md with 9789b584614345d512478c978a3f01787f360518.

I've been too lazy to test it with other versions of python. So I used the version of python my distribution ships. It nay work with other versions, too. We could add CI tests using tox. I'm open for contributions 😉

**Comment by asmcc** [comment]
Unfortunatelly I could not bring it to run with raspbian on my raspberry pi. Raspberry pi was too slow for me to build all the packages manually. These missing dependencies were observed by me at this raspbian.
At next step I tested it on my notebook with actual Linux Mint version (Ubuntu based). Here these libs was not missed and I could build and execute the script also with Python 3.8 (change in your configuration was required). It works, but it does not solve my problem with my broken brother printer. But this is another problem and will be resolved by the hardware flash of this printer.
About Python version. I use very actual linux distributions based on Ubuntu and Debian. Ubuntu and Mint use very new packages, but Python 3.9 is to new for it. The advantage of Debian-based Linix distributions is their strong package management. Therefore it is not usualy at these distributions to compile such packages like Python manually.

You can close this issue.

Thanks!
