### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by sveyret** [sedrubal/brother_printer_fwupd#4]
Hi,
Just to warn that in the README is written:
`pip install --user --upgrade brother-printer-fwupd`
while actually, the package is named with underscores, not dash. It should be:
`pip install --user --upgrade brother_printer_fwupd`

By the way, it worked with my printer, although already up to date: DCP-9020CDW

**Comment by sedrubal** [comment]
Hi @sveyret, thanks for your report. Actually I'm not sure, why there are dashes in the package name, but I think I've copied that command from https://pypi.org/project/brother_printer_fwupd/, which automatically redirects to https://pypi.org/project/brother-printer-fwupd/ . I assume, it makes not difference?

I added the `DCP-9020CDW` with c42c1a4, thanks!

**Comment by sveyret** [comment]
Strangely, it now works, indeed, even if I use dashes. But this morning, I had an error message, saying it could not find appropriate package, until I used the underscores.

**Comment by sveyret** [comment]
And, by the way, thank you for this project!
