### ISSUE TITLE
sorta broken with MFC-L3750CDW

### ISSUE THREAD

**Issue by nutterthanos** [sedrubal/brother_printer_fwupd#8]
```
←[34m[i] Querying printer info via SNMP.←[0m
←[34m[i]  Detected MFC-L3750CDW series with following firmware version(s): MAIN @ W2109141139:E619, SUB1 @ 1.59, SUB5 @ 1.00←[0m
←[34m[i] Querying firmware download URL from Brother update API.←[0m
←[31m[!] Did not receive download url for MAIN.←[0m
←[31m[!] Either this firmware part is up to date or there is a bug.←[0m
←[31m[!] This is the response of Brother's update API:←[0m
←[31m[!] <?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO></RESPONSEINFO>←[0m
←[31m[!] Did not receive download url for SUB1.←[0m
←[31m[!] Either this firmware part is up to date or there is a bug.←[0m
←[31m[!] This is the response of Brother's update API:←[0m
←[31m[!] <?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO></RESPONSEINFO>←[0m
←[31m[!] Unknown versioncheck response for firmid='SUB5'.←[0m
←[31m[!] There seems to be a bug. Open an issue!←[0m
←[31m[!] This is the response of Brother's update API:←[0m
←[31m[!] <?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK><FIRMID>SUB5</FIRMID></FIRMUPDATEINFO></RESPONSEINFO>←[0m
←[32m[i] Done.←[0m
```

**Comment by sedrubal** [comment]
These errors are hard to debug especially for me as I don't have this printer and currently I'm traveling and don't have a proper Internet connection. Do you have the opportunity to use the official firmware update software from brother to verify if there is an update for your printer? Maybe you can also try to find out which requests the official software sends to check for firmware updates.
Anyway, I just released v0.4.2 with better debugging facilities. Can you try it and post the full debug output here?

**Comment by nutterthanos** [comment]
i'll try tomorrow
EDIT: sorry i have not yet trying now

**Comment by nutterthanos** [comment]
←[36m[i] Querying printer info via SNMP.←[0m
←[32m[i] Detected MFC-L3750CDW series with following firmware version(s): MAIN@W2109141139:E619, SUB1@1.59, SUB5@1.00←[0m
←[36m[i] Querying firmware download URL from Brother update API.←[0m
←[30m[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>MAIN</FIRMCATEGORY>
        <OS>WINDOWS</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>MFC-L3750CDW series</NAME>
            <SPEC>0706</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>

        <FIRM>
            <ID>MAIN</ID>
            <VERSION>W2109141139:E619</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB1</ID>
            <VERSION>1.59</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>

            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
←[0m
←[30m[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO></RESPONSEINFO>←[0m
←[33m[!] Did not receive download url for MAIN.←[0m
←[33m[!] Either this firmware part is up to date or there is a bug.←[0m
←[30m[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB1</FIRMCATEGORY>
        <OS>WINDOWS</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>MFC-L3750CDW series</NAME>
            <SPEC>0706</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>

        <FIRM>
            <ID>MAIN</ID>
            <VERSION>W2109141139:E619</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB1</ID>
            <VERSION>1.59</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>

            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
←[0m
←[30m[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO></RESPONSEINFO>←[0m
←[33m[!] Did not receive download url for SUB1.←[0m
←[33m[!] Either this firmware part is up to date or there is a bug.←[0m
←[30m[d] Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB5</FIRMCATEGORY>
        <OS>WINDOWS</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>MFC-L3750CDW series</NAME>
            <SPEC>0706</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>

        <FIRM>
            <ID>MAIN</ID>
            <VERSION>W2109141139:E619</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB1</ID>
            <VERSION>1.59</VERSION>
        </FIRM>

        <FIRM>
            <ID>SUB5</ID>
            <VERSION>1.00</VERSION>
        </FIRM>

            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
←[0m
←[30m[d] Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK><FIRMID>SUB5</FIRMID></FIRMUPDATEINFO></RESPONSEINFO>←[0m
←[31m[!] Unknown versioncheck response for firmid=SUB5.←[0m
←[31m[!] There seems to be a bug.←[0m
←[31m[!] Open an issue with the full debug output: https://github.com/sedrubal/brother_printer_fwupd/issues/new←[0m
←[32m[i] Done.←[0m

**Comment by nutterthanos** [comment]
well its up to date
shouln't it be doing this
https://github.com/sedrubal/brother_printer_fwupd/blob/main/brother_printer_fwupd/firmware_downloader.py#L88

**Comment by sedrubal** [comment]
I'm closing this issue as I don't know how to determine if the printer is already up to date with this (imho broken / awkward) Brother API.

**Comment by nutterthanos** [comment]
No like if the printers version is up to date the server would not giving out any update urls

**Comment by sedrubal** [comment]
What would you recommend then? I found no way to interpret the codes the API returns. If you have any ideas how to improve the script, just open a pull request or let me know.

**Comment by nutterthanos** [comment]
https://pastebin.com/LbJUwKMH

**Comment by skissane** [comment]
FYI, I opened a new issue on (roughly) the same topic – https://github.com/sedrubal/brother_printer_fwupd/issues/19
